// Application-generated primary keys (docs/17_Database_Design.md §3):
// UUIDv7, time-ordered for index locality, generated by the application
// rather than by a database default — so an id exists before the first
// `INSERT` and callers never need a round trip to learn one.
import { randomBytes } from "node:crypto";

const HEX_GROUPS = [8, 4, 4, 4, 12] as const;

/**
 * RFC 9562 UUIDv7: a 48-bit millisecond timestamp, a 4-bit version, a
 * 2-bit variant, and 74 bits of randomness — sortable by creation time
 * without exposing a sequential counter (D-17-12).
 */
export function uuidv7(): string {
  const unixTsMs = BigInt(Date.now());
  const rand = randomBytes(10);
  const bytes = Buffer.alloc(16);

  bytes[0] = Number((unixTsMs >> 40n) & 0xffn);
  bytes[1] = Number((unixTsMs >> 32n) & 0xffn);
  bytes[2] = Number((unixTsMs >> 24n) & 0xffn);
  bytes[3] = Number((unixTsMs >> 16n) & 0xffn);
  bytes[4] = Number((unixTsMs >> 8n) & 0xffn);
  bytes[5] = Number(unixTsMs & 0xffn);
  bytes[6] = 0x70 | (rand[0]! & 0x0f); // version 7
  bytes[7] = rand[1]!;
  bytes[8] = 0x80 | (rand[2]! & 0x3f); // variant 10
  rand.copy(bytes, 9, 3, 10);

  const hex = bytes.toString("hex");
  let offset = 0;
  const parts: string[] = [];
  for (const length of HEX_GROUPS) {
    parts.push(hex.slice(offset, offset + length));
    offset += length;
  }
  return parts.join("-");
}
